# Generated by Django 5.2.2 on 2025-06-07 03:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=7)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(blank=True, help_text='Descripción del motivo (p.ej. ajuste, pérdida, etc.)', max_length=200)),
                ('referencia', models.CharField(blank=True, help_text='ID de Compra/Venta u otra referencia opcional', max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.producto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
