--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: alumnos_alumno; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.alumnos_alumno (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    apellido character varying(100) NOT NULL,
    grado character varying(50) NOT NULL,
    nivel character varying(50) NOT NULL,
    limite_consumo numeric(12,0) NOT NULL,
    saldo_tarjeta numeric(12,0) NOT NULL,
    numero_tarjeta character varying(20)
);


ALTER TABLE public.alumnos_alumno OWNER TO lgservice_user;

--
-- Name: alumnos_alumno_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.alumnos_alumno ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alumnos_alumno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alumnos_configuracionpagos; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.alumnos_configuracionpagos (
    id bigint NOT NULL,
    nombre_banco character varying(100) NOT NULL,
    titular_cuenta character varying(100) NOT NULL,
    numero_cuenta character varying(100) NOT NULL,
    ruc character varying(20),
    instrucciones text NOT NULL,
    monto_minimo numeric(10,0) NOT NULL,
    activo boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL
);


ALTER TABLE public.alumnos_configuracionpagos OWNER TO lgservice_user;

--
-- Name: alumnos_configuracionpagos_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.alumnos_configuracionpagos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alumnos_configuracionpagos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alumnos_notificacionpadre; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.alumnos_notificacionpadre (
    id bigint NOT NULL,
    tipo character varying(30) NOT NULL,
    mensaje text NOT NULL,
    leida boolean NOT NULL,
    fecha_hora timestamp with time zone NOT NULL,
    alumno_id bigint NOT NULL,
    padre_id bigint NOT NULL,
    transaccion_id bigint,
    venta_id bigint
);


ALTER TABLE public.alumnos_notificacionpadre OWNER TO lgservice_user;

--
-- Name: alumnos_notificacionpadre_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.alumnos_notificacionpadre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alumnos_notificacionpadre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alumnos_padre; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.alumnos_padre (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    apellido character varying(100) NOT NULL,
    razon_social character varying(150) NOT NULL,
    ruc character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    telefono character varying(20) NOT NULL,
    direccion text NOT NULL,
    barrio character varying(100) NOT NULL,
    ciudad character varying(100) NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.alumnos_padre OWNER TO lgservice_user;

--
-- Name: alumnos_padre_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.alumnos_padre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alumnos_padre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alumnos_relacionfamiliar; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.alumnos_relacionfamiliar (
    id bigint NOT NULL,
    es_tutor_principal boolean NOT NULL,
    puede_ver_movimientos boolean NOT NULL,
    puede_recibir_notificaciones boolean NOT NULL,
    puede_cargar_saldo boolean NOT NULL,
    puede_modificar_restricciones boolean NOT NULL,
    alumno_id bigint NOT NULL,
    padre_id bigint NOT NULL
);


ALTER TABLE public.alumnos_relacionfamiliar OWNER TO lgservice_user;

--
-- Name: alumnos_relacionfamiliar_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.alumnos_relacionfamiliar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alumnos_relacionfamiliar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alumnos_restriccion; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.alumnos_restriccion (
    id bigint NOT NULL,
    permitido boolean NOT NULL,
    alumno_id bigint NOT NULL,
    producto_id bigint NOT NULL
);


ALTER TABLE public.alumnos_restriccion OWNER TO lgservice_user;

--
-- Name: alumnos_restriccion_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.alumnos_restriccion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alumnos_restriccion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alumnos_transaccionsaldo; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.alumnos_transaccionsaldo (
    id bigint NOT NULL,
    monto numeric(10,0) NOT NULL,
    fecha_hora timestamp with time zone NOT NULL,
    metodo_pago character varying(20) NOT NULL,
    estado character varying(20) NOT NULL,
    referencia_pago character varying(100),
    comprobante character varying(100),
    notas text,
    motivo_rechazo character varying(255),
    fecha_validacion timestamp with time zone,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_modificacion timestamp with time zone NOT NULL,
    alumno_id bigint NOT NULL,
    realizada_por_id bigint,
    validada_por_id bigint
);


ALTER TABLE public.alumnos_transaccionsaldo OWNER TO lgservice_user;

--
-- Name: alumnos_transaccionsaldo_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.alumnos_transaccionsaldo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alumnos_transaccionsaldo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO lgservice_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO lgservice_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO lgservice_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: compras_compra; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.compras_compra (
    id bigint NOT NULL,
    numero_factura character varying(50) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    total numeric(10,2) NOT NULL,
    pagada boolean NOT NULL,
    notas text NOT NULL,
    proveedor_id bigint NOT NULL
);


ALTER TABLE public.compras_compra OWNER TO lgservice_user;

--
-- Name: compras_compra_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.compras_compra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compras_compra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: compras_detallecompra; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.compras_detallecompra (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    compra_id bigint NOT NULL,
    producto_id bigint NOT NULL,
    CONSTRAINT compras_detallecompra_cantidad_check CHECK ((cantidad >= 0))
);


ALTER TABLE public.compras_detallecompra OWNER TO lgservice_user;

--
-- Name: compras_detallecompra_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.compras_detallecompra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compras_detallecompra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configuracion_configuracionsistema; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.configuracion_configuracionsistema (
    id bigint NOT NULL,
    nombre_sistema character varying(100) NOT NULL,
    moneda character varying(10) NOT NULL,
    limite_credito numeric(10,2) NOT NULL,
    horario_atencion character varying(100) NOT NULL,
    color_principal character varying(20) NOT NULL,
    logo character varying(100)
);


ALTER TABLE public.configuracion_configuracionsistema OWNER TO lgservice_user;

--
-- Name: configuracion_configuracionsistema_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.configuracion_configuracionsistema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.configuracion_configuracionsistema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO lgservice_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO lgservice_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO lgservice_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO lgservice_user;

--
-- Name: facturacion_factura; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.facturacion_factura (
    id bigint NOT NULL,
    numero character varying(20) NOT NULL,
    fecha_emision timestamp with time zone NOT NULL,
    ruc character varying(20),
    razon_social character varying(255),
    direccion character varying(255),
    total numeric(12,2) NOT NULL,
    venta_id bigint NOT NULL
);


ALTER TABLE public.facturacion_factura OWNER TO lgservice_user;

--
-- Name: facturacion_factura_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.facturacion_factura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.facturacion_factura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos_categoria; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.productos_categoria (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    activa boolean NOT NULL
);


ALTER TABLE public.productos_categoria OWNER TO lgservice_user;

--
-- Name: productos_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.productos_categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos_movimientostock; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.productos_movimientostock (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    tipo_movimiento character varying(20) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    nota text,
    producto_id bigint NOT NULL,
    usuario_id bigint
);


ALTER TABLE public.productos_movimientostock OWNER TO lgservice_user;

--
-- Name: productos_movimientostock_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.productos_movimientostock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_movimientostock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos_producto; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.productos_producto (
    id bigint NOT NULL,
    codigo character varying(50) NOT NULL,
    codigo_barras character varying(50),
    nombre character varying(100) NOT NULL,
    descripcion text,
    cantidad integer NOT NULL,
    cantidad_minima integer NOT NULL,
    precio_costo numeric(10,2) NOT NULL,
    precio_venta numeric(10,2) NOT NULL,
    imagen character varying(100),
    estado character varying(15) NOT NULL,
    destacado boolean NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    fecha_actualizacion timestamp with time zone NOT NULL,
    fecha_ultimo_pedido timestamp with time zone,
    categoria_id bigint,
    proveedor_id bigint,
    CONSTRAINT productos_producto_cantidad_check CHECK ((cantidad >= 0)),
    CONSTRAINT productos_producto_cantidad_minima_check CHECK ((cantidad_minima >= 0))
);


ALTER TABLE public.productos_producto OWNER TO lgservice_user;

--
-- Name: productos_producto_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.productos_producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proveedores_proveedor; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.proveedores_proveedor (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    direccion text,
    telefono character varying(20),
    email character varying(254),
    sitio_web character varying(200),
    notas text,
    activo boolean NOT NULL
);


ALTER TABLE public.proveedores_proveedor OWNER TO lgservice_user;

--
-- Name: proveedores_proveedor_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.proveedores_proveedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proveedores_proveedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuariolg; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.usuarios_usuariolg (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    tipo character varying(7) NOT NULL
);


ALTER TABLE public.usuarios_usuariolg OWNER TO lgservice_user;

--
-- Name: usuarios_usuariolg_groups; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.usuarios_usuariolg_groups (
    id bigint NOT NULL,
    usuariolg_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.usuarios_usuariolg_groups OWNER TO lgservice_user;

--
-- Name: usuarios_usuariolg_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.usuarios_usuariolg_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuariolg_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuariolg_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.usuarios_usuariolg ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuariolg_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuariolg_user_permissions; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.usuarios_usuariolg_user_permissions (
    id bigint NOT NULL,
    usuariolg_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.usuarios_usuariolg_user_permissions OWNER TO lgservice_user;

--
-- Name: usuarios_usuariolg_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.usuarios_usuariolg_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuariolg_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventas_authorizationcode; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.ventas_authorizationcode (
    id bigint NOT NULL,
    codigo uuid NOT NULL,
    fecha timestamp with time zone NOT NULL,
    descripcion character varying(255),
    venta_id bigint NOT NULL
);


ALTER TABLE public.ventas_authorizationcode OWNER TO lgservice_user;

--
-- Name: ventas_authorizationcode_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.ventas_authorizationcode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_authorizationcode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventas_caja; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.ventas_caja (
    id bigint NOT NULL,
    numero integer NOT NULL,
    nombre character varying(50) NOT NULL,
    ubicacion character varying(100) NOT NULL,
    activa boolean NOT NULL,
    CONSTRAINT ventas_caja_numero_check CHECK ((numero >= 0))
);


ALTER TABLE public.ventas_caja OWNER TO lgservice_user;

--
-- Name: ventas_caja_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.ventas_caja ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_caja_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventas_detalleventa; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.ventas_detalleventa (
    id bigint NOT NULL,
    cantidad numeric(10,3) NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    descuento_item numeric(10,2) NOT NULL,
    producto_id bigint NOT NULL,
    venta_id bigint NOT NULL
);


ALTER TABLE public.ventas_detalleventa OWNER TO lgservice_user;

--
-- Name: ventas_detalleventa_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.ventas_detalleventa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_detalleventa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventas_metodopago; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.ventas_metodopago (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    descripcion text,
    activo boolean NOT NULL,
    requiere_referencia boolean NOT NULL
);


ALTER TABLE public.ventas_metodopago OWNER TO lgservice_user;

--
-- Name: ventas_metodopago_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.ventas_metodopago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_metodopago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventas_pagoventa; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.ventas_pagoventa (
    id bigint NOT NULL,
    metodo character varying(20) NOT NULL,
    monto numeric(10,2) NOT NULL,
    tasa numeric(5,2) NOT NULL,
    monto_final numeric(10,2) NOT NULL,
    referencia character varying(100),
    observacion character varying(255),
    fecha timestamp with time zone NOT NULL,
    metodo_pago_id bigint,
    venta_id bigint NOT NULL
);


ALTER TABLE public.ventas_pagoventa OWNER TO lgservice_user;

--
-- Name: ventas_pagoventa_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.ventas_pagoventa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_pagoventa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventas_reportecaja; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.ventas_reportecaja (
    id bigint NOT NULL,
    fecha date NOT NULL,
    turnos_total integer NOT NULL,
    ventas_total integer NOT NULL,
    monto_total numeric(12,2) NOT NULL,
    diferencias_total numeric(10,2) NOT NULL,
    generado_el timestamp with time zone NOT NULL,
    caja_id bigint NOT NULL,
    CONSTRAINT ventas_reportecaja_turnos_total_check CHECK ((turnos_total >= 0)),
    CONSTRAINT ventas_reportecaja_ventas_total_check CHECK ((ventas_total >= 0))
);


ALTER TABLE public.ventas_reportecaja OWNER TO lgservice_user;

--
-- Name: ventas_reportecaja_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.ventas_reportecaja ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_reportecaja_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventas_turnocajero; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.ventas_turnocajero (
    id bigint NOT NULL,
    fecha_inicio timestamp with time zone NOT NULL,
    fecha_fin timestamp with time zone,
    monto_inicial numeric(10,2) NOT NULL,
    monto_final numeric(10,2),
    observaciones_apertura text,
    observaciones_cierre text,
    activa boolean NOT NULL,
    caja_id bigint NOT NULL,
    cajero_id bigint NOT NULL
);


ALTER TABLE public.ventas_turnocajero OWNER TO lgservice_user;

--
-- Name: ventas_turnocajero_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.ventas_turnocajero ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_turnocajero_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventas_venta; Type: TABLE; Schema: public; Owner: lgservice_user
--

CREATE TABLE public.ventas_venta (
    id bigint NOT NULL,
    numero_venta character varying(50) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    condicion character varying(10) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    descuento numeric(10,2) NOT NULL,
    total numeric(10,2) NOT NULL,
    estado character varying(15) NOT NULL,
    observaciones text,
    fecha_completada timestamp with time zone,
    fecha_cancelada timestamp with time zone,
    motivo_cancelacion text,
    cajero_id bigint NOT NULL,
    cliente_id bigint,
    turno_cajero_id bigint NOT NULL
);


ALTER TABLE public.ventas_venta OWNER TO lgservice_user;

--
-- Name: ventas_venta_id_seq; Type: SEQUENCE; Schema: public; Owner: lgservice_user
--

ALTER TABLE public.ventas_venta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_venta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: alumnos_alumno; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.alumnos_alumno (id, nombre, apellido, grado, nivel, limite_consumo, saldo_tarjeta, numero_tarjeta) FROM stdin;
\.


--
-- Data for Name: alumnos_configuracionpagos; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.alumnos_configuracionpagos (id, nombre_banco, titular_cuenta, numero_cuenta, ruc, instrucciones, monto_minimo, activo, fecha_creacion, fecha_modificacion) FROM stdin;
\.


--
-- Data for Name: alumnos_notificacionpadre; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.alumnos_notificacionpadre (id, tipo, mensaje, leida, fecha_hora, alumno_id, padre_id, transaccion_id, venta_id) FROM stdin;
\.


--
-- Data for Name: alumnos_padre; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.alumnos_padre (id, nombre, apellido, razon_social, ruc, email, telefono, direccion, barrio, ciudad, usuario_id) FROM stdin;
\.


--
-- Data for Name: alumnos_relacionfamiliar; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.alumnos_relacionfamiliar (id, es_tutor_principal, puede_ver_movimientos, puede_recibir_notificaciones, puede_cargar_saldo, puede_modificar_restricciones, alumno_id, padre_id) FROM stdin;
\.


--
-- Data for Name: alumnos_restriccion; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.alumnos_restriccion (id, permitido, alumno_id, producto_id) FROM stdin;
\.


--
-- Data for Name: alumnos_transaccionsaldo; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.alumnos_transaccionsaldo (id, monto, fecha_hora, metodo_pago, estado, referencia_pago, comprobante, notas, motivo_rechazo, fecha_validacion, fecha_creacion, fecha_modificacion, alumno_id, realizada_por_id, validada_por_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Usuario	6	add_usuariolg
22	Can change Usuario	6	change_usuariolg
23	Can delete Usuario	6	delete_usuariolg
24	Can view Usuario	6	view_usuariolg
25	Can add Alumno	7	add_alumno
26	Can change Alumno	7	change_alumno
27	Can delete Alumno	7	delete_alumno
28	Can view Alumno	7	view_alumno
29	Can add Configuración de Pagos	8	add_configuracionpagos
30	Can change Configuración de Pagos	8	change_configuracionpagos
31	Can delete Configuración de Pagos	8	delete_configuracionpagos
32	Can view Configuración de Pagos	8	view_configuracionpagos
33	Can add Notificación	9	add_notificacionpadre
34	Can change Notificación	9	change_notificacionpadre
35	Can delete Notificación	9	delete_notificacionpadre
36	Can view Notificación	9	view_notificacionpadre
37	Can add padre	10	add_padre
38	Can change padre	10	change_padre
39	Can delete padre	10	delete_padre
40	Can view padre	10	view_padre
41	Can add Relación Familiar	11	add_relacionfamiliar
42	Can change Relación Familiar	11	change_relacionfamiliar
43	Can delete Relación Familiar	11	delete_relacionfamiliar
44	Can view Relación Familiar	11	view_relacionfamiliar
45	Can add Restricción	12	add_restriccion
46	Can change Restricción	12	change_restriccion
47	Can delete Restricción	12	delete_restriccion
48	Can view Restricción	12	view_restriccion
49	Can add Transacción de Saldo	13	add_transaccionsaldo
50	Can change Transacción de Saldo	13	change_transaccionsaldo
51	Can delete Transacción de Saldo	13	delete_transaccionsaldo
52	Can view Transacción de Saldo	13	view_transaccionsaldo
53	Can add Categoría	14	add_categoria
54	Can change Categoría	14	change_categoria
55	Can delete Categoría	14	delete_categoria
56	Can view Categoría	14	view_categoria
57	Can add Producto	15	add_producto
58	Can change Producto	15	change_producto
59	Can delete Producto	15	delete_producto
60	Can view Producto	15	view_producto
61	Can add Movimiento de Stock	16	add_movimientostock
62	Can change Movimiento de Stock	16	change_movimientostock
63	Can delete Movimiento de Stock	16	delete_movimientostock
64	Can view Movimiento de Stock	16	view_movimientostock
65	Can add Caja	17	add_caja
66	Can change Caja	17	change_caja
67	Can delete Caja	17	delete_caja
68	Can view Caja	17	view_caja
69	Can add Método de Pago	18	add_metodopago
70	Can change Método de Pago	18	change_metodopago
71	Can delete Método de Pago	18	delete_metodopago
72	Can view Método de Pago	18	view_metodopago
73	Can add Turno de Cajero	19	add_turnocajero
74	Can change Turno de Cajero	19	change_turnocajero
75	Can delete Turno de Cajero	19	delete_turnocajero
76	Can view Turno de Cajero	19	view_turnocajero
77	Can add Venta	20	add_venta
78	Can change Venta	20	change_venta
79	Can delete Venta	20	delete_venta
80	Can view Venta	20	view_venta
81	Can add Pago de Venta	21	add_pagoventa
82	Can change Pago de Venta	21	change_pagoventa
83	Can delete Pago de Venta	21	delete_pagoventa
84	Can view Pago de Venta	21	view_pagoventa
85	Can add Detalle de Venta	22	add_detalleventa
86	Can change Detalle de Venta	22	change_detalleventa
87	Can delete Detalle de Venta	22	delete_detalleventa
88	Can view Detalle de Venta	22	view_detalleventa
89	Can add authorization code	23	add_authorizationcode
90	Can change authorization code	23	change_authorizationcode
91	Can delete authorization code	23	delete_authorizationcode
92	Can view authorization code	23	view_authorizationcode
93	Can add Reporte de Caja	24	add_reportecaja
94	Can change Reporte de Caja	24	change_reportecaja
95	Can delete Reporte de Caja	24	delete_reportecaja
96	Can view Reporte de Caja	24	view_reportecaja
97	Can add Proveedor	25	add_proveedor
98	Can change Proveedor	25	change_proveedor
99	Can delete Proveedor	25	delete_proveedor
100	Can view Proveedor	25	view_proveedor
101	Can add Compra	26	add_compra
102	Can change Compra	26	change_compra
103	Can delete Compra	26	delete_compra
104	Can view Compra	26	view_compra
105	Can add detalle compra	27	add_detallecompra
106	Can change detalle compra	27	change_detallecompra
107	Can delete detalle compra	27	delete_detallecompra
108	Can view detalle compra	27	view_detallecompra
109	Can add Factura	28	add_factura
110	Can change Factura	28	change_factura
111	Can delete Factura	28	delete_factura
112	Can view Factura	28	view_factura
113	Can add configuracion sistema	29	add_configuracionsistema
114	Can change configuracion sistema	29	change_configuracionsistema
115	Can delete configuracion sistema	29	delete_configuracionsistema
116	Can view configuracion sistema	29	view_configuracionsistema
\.


--
-- Data for Name: compras_compra; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.compras_compra (id, numero_factura, fecha, total, pagada, notas, proveedor_id) FROM stdin;
\.


--
-- Data for Name: compras_detallecompra; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.compras_detallecompra (id, cantidad, precio_unitario, compra_id, producto_id) FROM stdin;
\.


--
-- Data for Name: configuracion_configuracionsistema; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.configuracion_configuracionsistema (id, nombre_sistema, moneda, limite_credito, horario_atencion, color_principal, logo) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	usuarios	usuariolg
7	alumnos	alumno
8	alumnos	configuracionpagos
9	alumnos	notificacionpadre
10	alumnos	padre
11	alumnos	relacionfamiliar
12	alumnos	restriccion
13	alumnos	transaccionsaldo
14	productos	categoria
15	productos	producto
16	productos	movimientostock
17	ventas	caja
18	ventas	metodopago
19	ventas	turnocajero
20	ventas	venta
21	ventas	pagoventa
22	ventas	detalleventa
23	ventas	authorizationcode
24	ventas	reportecaja
25	proveedores	proveedor
26	compras	compra
27	compras	detallecompra
28	facturacion	factura
29	configuracion	configuracionsistema
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-09-08 23:55:04.70309-03
2	contenttypes	0002_remove_content_type_name	2025-09-08 23:55:04.712036-03
3	auth	0001_initial	2025-09-08 23:55:04.778402-03
4	auth	0002_alter_permission_name_max_length	2025-09-08 23:55:04.784242-03
5	auth	0003_alter_user_email_max_length	2025-09-08 23:55:04.790649-03
6	auth	0004_alter_user_username_opts	2025-09-08 23:55:04.797554-03
7	auth	0005_alter_user_last_login_null	2025-09-08 23:55:04.806714-03
8	auth	0006_require_contenttypes_0002	2025-09-08 23:55:04.811094-03
9	auth	0007_alter_validators_add_error_messages	2025-09-08 23:55:04.818682-03
10	auth	0008_alter_user_username_max_length	2025-09-08 23:55:04.825982-03
11	auth	0009_alter_user_last_name_max_length	2025-09-08 23:55:04.833402-03
12	auth	0010_alter_group_name_max_length	2025-09-08 23:55:04.842655-03
13	auth	0011_update_proxy_permissions	2025-09-08 23:55:04.850022-03
14	auth	0012_alter_user_first_name_max_length	2025-09-08 23:55:04.857753-03
15	usuarios	0001_initial	2025-09-08 23:55:04.91412-03
16	admin	0001_initial	2025-09-08 23:55:04.93816-03
17	admin	0002_logentry_remove_auto_add	2025-09-08 23:55:04.946599-03
18	admin	0003_logentry_add_action_flag_choices	2025-09-08 23:55:04.953549-03
19	proveedores	0001_initial	2025-09-08 23:55:04.968776-03
20	productos	0001_initial	2025-09-08 23:55:05.026778-03
21	alumnos	0001_initial	2025-09-08 23:55:05.086776-03
22	ventas	0001_initial	2025-09-08 23:55:05.263262-03
23	alumnos	0002_initial	2025-09-08 23:55:05.517391-03
24	compras	0001_initial	2025-09-08 23:55:05.550534-03
25	compras	0002_initial	2025-09-08 23:55:05.598007-03
26	configuracion	0001_initial	2025-09-08 23:55:05.610195-03
27	facturacion	0001_initial	2025-09-08 23:55:05.63388-03
28	facturacion	0002_initial	2025-09-08 23:55:05.659644-03
29	productos	0002_initial	2025-09-08 23:55:05.727071-03
30	sessions	0001_initial	2025-09-08 23:55:05.750457-03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: facturacion_factura; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.facturacion_factura (id, numero, fecha_emision, ruc, razon_social, direccion, total, venta_id) FROM stdin;
\.


--
-- Data for Name: productos_categoria; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.productos_categoria (id, nombre, descripcion, activa) FROM stdin;
\.


--
-- Data for Name: productos_movimientostock; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.productos_movimientostock (id, cantidad, tipo_movimiento, fecha, nota, producto_id, usuario_id) FROM stdin;
\.


--
-- Data for Name: productos_producto; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.productos_producto (id, codigo, codigo_barras, nombre, descripcion, cantidad, cantidad_minima, precio_costo, precio_venta, imagen, estado, destacado, fecha_creacion, fecha_actualizacion, fecha_ultimo_pedido, categoria_id, proveedor_id) FROM stdin;
\.


--
-- Data for Name: proveedores_proveedor; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.proveedores_proveedor (id, nombre, direccion, telefono, email, sitio_web, notas, activo) FROM stdin;
\.


--
-- Data for Name: usuarios_usuariolg; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.usuarios_usuariolg (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, tipo) FROM stdin;
1	pbkdf2_sha256$600000$N5Q4gp4QYGXVXJXhzy8BlT$DoZsulWc+jyZVGqw+nJa57cfMVTVRFFVGjv9JSZdOAg=	\N	t	Lucas			l@l.com	t	t	2025-09-09 00:01:38.410561-03	
\.


--
-- Data for Name: usuarios_usuariolg_groups; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.usuarios_usuariolg_groups (id, usuariolg_id, group_id) FROM stdin;
\.


--
-- Data for Name: usuarios_usuariolg_user_permissions; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.usuarios_usuariolg_user_permissions (id, usuariolg_id, permission_id) FROM stdin;
\.


--
-- Data for Name: ventas_authorizationcode; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.ventas_authorizationcode (id, codigo, fecha, descripcion, venta_id) FROM stdin;
\.


--
-- Data for Name: ventas_caja; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.ventas_caja (id, numero, nombre, ubicacion, activa) FROM stdin;
\.


--
-- Data for Name: ventas_detalleventa; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.ventas_detalleventa (id, cantidad, precio_unitario, descuento_item, producto_id, venta_id) FROM stdin;
\.


--
-- Data for Name: ventas_metodopago; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.ventas_metodopago (id, nombre, descripcion, activo, requiere_referencia) FROM stdin;
\.


--
-- Data for Name: ventas_pagoventa; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.ventas_pagoventa (id, metodo, monto, tasa, monto_final, referencia, observacion, fecha, metodo_pago_id, venta_id) FROM stdin;
\.


--
-- Data for Name: ventas_reportecaja; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.ventas_reportecaja (id, fecha, turnos_total, ventas_total, monto_total, diferencias_total, generado_el, caja_id) FROM stdin;
\.


--
-- Data for Name: ventas_turnocajero; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.ventas_turnocajero (id, fecha_inicio, fecha_fin, monto_inicial, monto_final, observaciones_apertura, observaciones_cierre, activa, caja_id, cajero_id) FROM stdin;
\.


--
-- Data for Name: ventas_venta; Type: TABLE DATA; Schema: public; Owner: lgservice_user
--

COPY public.ventas_venta (id, numero_venta, fecha, condicion, subtotal, descuento, total, estado, observaciones, fecha_completada, fecha_cancelada, motivo_cancelacion, cajero_id, cliente_id, turno_cajero_id) FROM stdin;
\.


--
-- Name: alumnos_alumno_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.alumnos_alumno_id_seq', 1, false);


--
-- Name: alumnos_configuracionpagos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.alumnos_configuracionpagos_id_seq', 1, false);


--
-- Name: alumnos_notificacionpadre_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.alumnos_notificacionpadre_id_seq', 1, false);


--
-- Name: alumnos_padre_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.alumnos_padre_id_seq', 1, false);


--
-- Name: alumnos_relacionfamiliar_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.alumnos_relacionfamiliar_id_seq', 1, false);


--
-- Name: alumnos_restriccion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.alumnos_restriccion_id_seq', 1, false);


--
-- Name: alumnos_transaccionsaldo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.alumnos_transaccionsaldo_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 116, true);


--
-- Name: compras_compra_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.compras_compra_id_seq', 1, false);


--
-- Name: compras_detallecompra_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.compras_detallecompra_id_seq', 1, false);


--
-- Name: configuracion_configuracionsistema_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.configuracion_configuracionsistema_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 29, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 30, true);


--
-- Name: facturacion_factura_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.facturacion_factura_id_seq', 1, false);


--
-- Name: productos_categoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.productos_categoria_id_seq', 1, false);


--
-- Name: productos_movimientostock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.productos_movimientostock_id_seq', 1, false);


--
-- Name: productos_producto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.productos_producto_id_seq', 1, false);


--
-- Name: proveedores_proveedor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.proveedores_proveedor_id_seq', 1, false);


--
-- Name: usuarios_usuariolg_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.usuarios_usuariolg_groups_id_seq', 1, false);


--
-- Name: usuarios_usuariolg_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.usuarios_usuariolg_id_seq', 1, true);


--
-- Name: usuarios_usuariolg_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.usuarios_usuariolg_user_permissions_id_seq', 1, false);


--
-- Name: ventas_authorizationcode_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.ventas_authorizationcode_id_seq', 1, false);


--
-- Name: ventas_caja_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.ventas_caja_id_seq', 1, false);


--
-- Name: ventas_detalleventa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.ventas_detalleventa_id_seq', 1, false);


--
-- Name: ventas_metodopago_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.ventas_metodopago_id_seq', 1, false);


--
-- Name: ventas_pagoventa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.ventas_pagoventa_id_seq', 1, false);


--
-- Name: ventas_reportecaja_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.ventas_reportecaja_id_seq', 1, false);


--
-- Name: ventas_turnocajero_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.ventas_turnocajero_id_seq', 1, false);


--
-- Name: ventas_venta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: lgservice_user
--

SELECT pg_catalog.setval('public.ventas_venta_id_seq', 1, false);


--
-- Name: alumnos_alumno alumnos_alumno_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_alumno
    ADD CONSTRAINT alumnos_alumno_pkey PRIMARY KEY (id);


--
-- Name: alumnos_configuracionpagos alumnos_configuracionpagos_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_configuracionpagos
    ADD CONSTRAINT alumnos_configuracionpagos_pkey PRIMARY KEY (id);


--
-- Name: alumnos_notificacionpadre alumnos_notificacionpadre_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_notificacionpadre
    ADD CONSTRAINT alumnos_notificacionpadre_pkey PRIMARY KEY (id);


--
-- Name: alumnos_padre alumnos_padre_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_padre
    ADD CONSTRAINT alumnos_padre_pkey PRIMARY KEY (id);


--
-- Name: alumnos_padre alumnos_padre_usuario_id_key; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_padre
    ADD CONSTRAINT alumnos_padre_usuario_id_key UNIQUE (usuario_id);


--
-- Name: alumnos_relacionfamiliar alumnos_relacionfamiliar_padre_id_alumno_id_96f35a0f_uniq; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_relacionfamiliar
    ADD CONSTRAINT alumnos_relacionfamiliar_padre_id_alumno_id_96f35a0f_uniq UNIQUE (padre_id, alumno_id);


--
-- Name: alumnos_relacionfamiliar alumnos_relacionfamiliar_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_relacionfamiliar
    ADD CONSTRAINT alumnos_relacionfamiliar_pkey PRIMARY KEY (id);


--
-- Name: alumnos_restriccion alumnos_restriccion_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_restriccion
    ADD CONSTRAINT alumnos_restriccion_pkey PRIMARY KEY (id);


--
-- Name: alumnos_transaccionsaldo alumnos_transaccionsaldo_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_transaccionsaldo
    ADD CONSTRAINT alumnos_transaccionsaldo_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: compras_compra compras_compra_numero_factura_key; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.compras_compra
    ADD CONSTRAINT compras_compra_numero_factura_key UNIQUE (numero_factura);


--
-- Name: compras_compra compras_compra_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.compras_compra
    ADD CONSTRAINT compras_compra_pkey PRIMARY KEY (id);


--
-- Name: compras_detallecompra compras_detallecompra_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.compras_detallecompra
    ADD CONSTRAINT compras_detallecompra_pkey PRIMARY KEY (id);


--
-- Name: configuracion_configuracionsistema configuracion_configuracionsistema_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.configuracion_configuracionsistema
    ADD CONSTRAINT configuracion_configuracionsistema_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: facturacion_factura facturacion_factura_numero_key; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.facturacion_factura
    ADD CONSTRAINT facturacion_factura_numero_key UNIQUE (numero);


--
-- Name: facturacion_factura facturacion_factura_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.facturacion_factura
    ADD CONSTRAINT facturacion_factura_pkey PRIMARY KEY (id);


--
-- Name: facturacion_factura facturacion_factura_venta_id_key; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.facturacion_factura
    ADD CONSTRAINT facturacion_factura_venta_id_key UNIQUE (venta_id);


--
-- Name: productos_categoria productos_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.productos_categoria
    ADD CONSTRAINT productos_categoria_pkey PRIMARY KEY (id);


--
-- Name: productos_movimientostock productos_movimientostock_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.productos_movimientostock
    ADD CONSTRAINT productos_movimientostock_pkey PRIMARY KEY (id);


--
-- Name: productos_producto productos_producto_codigo_key; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.productos_producto
    ADD CONSTRAINT productos_producto_codigo_key UNIQUE (codigo);


--
-- Name: productos_producto productos_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.productos_producto
    ADD CONSTRAINT productos_producto_pkey PRIMARY KEY (id);


--
-- Name: proveedores_proveedor proveedores_proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.proveedores_proveedor
    ADD CONSTRAINT proveedores_proveedor_pkey PRIMARY KEY (id);


--
-- Name: alumnos_restriccion unique_restriccion_alumno_producto; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_restriccion
    ADD CONSTRAINT unique_restriccion_alumno_producto UNIQUE (alumno_id, producto_id);


--
-- Name: usuarios_usuariolg_groups usuarios_usuariolg_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.usuarios_usuariolg_groups
    ADD CONSTRAINT usuarios_usuariolg_groups_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuariolg_groups usuarios_usuariolg_groups_usuariolg_id_group_id_8f12f250_uniq; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.usuarios_usuariolg_groups
    ADD CONSTRAINT usuarios_usuariolg_groups_usuariolg_id_group_id_8f12f250_uniq UNIQUE (usuariolg_id, group_id);


--
-- Name: usuarios_usuariolg usuarios_usuariolg_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.usuarios_usuariolg
    ADD CONSTRAINT usuarios_usuariolg_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuariolg_user_permissions usuarios_usuariolg_user__usuariolg_id_permission__72f2e452_uniq; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.usuarios_usuariolg_user_permissions
    ADD CONSTRAINT usuarios_usuariolg_user__usuariolg_id_permission__72f2e452_uniq UNIQUE (usuariolg_id, permission_id);


--
-- Name: usuarios_usuariolg_user_permissions usuarios_usuariolg_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.usuarios_usuariolg_user_permissions
    ADD CONSTRAINT usuarios_usuariolg_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuariolg usuarios_usuariolg_username_key; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.usuarios_usuariolg
    ADD CONSTRAINT usuarios_usuariolg_username_key UNIQUE (username);


--
-- Name: ventas_authorizationcode ventas_authorizationcode_codigo_key; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_authorizationcode
    ADD CONSTRAINT ventas_authorizationcode_codigo_key UNIQUE (codigo);


--
-- Name: ventas_authorizationcode ventas_authorizationcode_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_authorizationcode
    ADD CONSTRAINT ventas_authorizationcode_pkey PRIMARY KEY (id);


--
-- Name: ventas_caja ventas_caja_numero_key; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_caja
    ADD CONSTRAINT ventas_caja_numero_key UNIQUE (numero);


--
-- Name: ventas_caja ventas_caja_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_caja
    ADD CONSTRAINT ventas_caja_pkey PRIMARY KEY (id);


--
-- Name: ventas_detalleventa ventas_detalleventa_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_detalleventa
    ADD CONSTRAINT ventas_detalleventa_pkey PRIMARY KEY (id);


--
-- Name: ventas_metodopago ventas_metodopago_nombre_key; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_metodopago
    ADD CONSTRAINT ventas_metodopago_nombre_key UNIQUE (nombre);


--
-- Name: ventas_metodopago ventas_metodopago_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_metodopago
    ADD CONSTRAINT ventas_metodopago_pkey PRIMARY KEY (id);


--
-- Name: ventas_pagoventa ventas_pagoventa_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_pagoventa
    ADD CONSTRAINT ventas_pagoventa_pkey PRIMARY KEY (id);


--
-- Name: ventas_reportecaja ventas_reportecaja_fecha_caja_id_04a48cd1_uniq; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_reportecaja
    ADD CONSTRAINT ventas_reportecaja_fecha_caja_id_04a48cd1_uniq UNIQUE (fecha, caja_id);


--
-- Name: ventas_reportecaja ventas_reportecaja_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_reportecaja
    ADD CONSTRAINT ventas_reportecaja_pkey PRIMARY KEY (id);


--
-- Name: ventas_turnocajero ventas_turnocajero_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_turnocajero
    ADD CONSTRAINT ventas_turnocajero_pkey PRIMARY KEY (id);


--
-- Name: ventas_venta ventas_venta_numero_venta_key; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_venta
    ADD CONSTRAINT ventas_venta_numero_venta_key UNIQUE (numero_venta);


--
-- Name: ventas_venta ventas_venta_pkey; Type: CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_venta
    ADD CONSTRAINT ventas_venta_pkey PRIMARY KEY (id);


--
-- Name: alumnos_notificacionpadre_alumno_id_b844dd96; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX alumnos_notificacionpadre_alumno_id_b844dd96 ON public.alumnos_notificacionpadre USING btree (alumno_id);


--
-- Name: alumnos_notificacionpadre_padre_id_e22c6c55; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX alumnos_notificacionpadre_padre_id_e22c6c55 ON public.alumnos_notificacionpadre USING btree (padre_id);


--
-- Name: alumnos_notificacionpadre_transaccion_id_2a6a818d; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX alumnos_notificacionpadre_transaccion_id_2a6a818d ON public.alumnos_notificacionpadre USING btree (transaccion_id);


--
-- Name: alumnos_notificacionpadre_venta_id_d8d6d2f5; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX alumnos_notificacionpadre_venta_id_d8d6d2f5 ON public.alumnos_notificacionpadre USING btree (venta_id);


--
-- Name: alumnos_relacionfamiliar_alumno_id_11dc7f0a; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX alumnos_relacionfamiliar_alumno_id_11dc7f0a ON public.alumnos_relacionfamiliar USING btree (alumno_id);


--
-- Name: alumnos_relacionfamiliar_padre_id_b20e606e; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX alumnos_relacionfamiliar_padre_id_b20e606e ON public.alumnos_relacionfamiliar USING btree (padre_id);


--
-- Name: alumnos_restriccion_alumno_id_15a1a8ba; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX alumnos_restriccion_alumno_id_15a1a8ba ON public.alumnos_restriccion USING btree (alumno_id);


--
-- Name: alumnos_restriccion_producto_id_c8ff6278; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX alumnos_restriccion_producto_id_c8ff6278 ON public.alumnos_restriccion USING btree (producto_id);


--
-- Name: alumnos_tra_alumno__ea0be1_idx; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX alumnos_tra_alumno__ea0be1_idx ON public.alumnos_transaccionsaldo USING btree (alumno_id, estado);


--
-- Name: alumnos_tra_estado_8bb963_idx; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX alumnos_tra_estado_8bb963_idx ON public.alumnos_transaccionsaldo USING btree (estado, fecha_hora);


--
-- Name: alumnos_transaccionsaldo_alumno_id_05386095; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX alumnos_transaccionsaldo_alumno_id_05386095 ON public.alumnos_transaccionsaldo USING btree (alumno_id);


--
-- Name: alumnos_transaccionsaldo_realizada_por_id_ef7132f7; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX alumnos_transaccionsaldo_realizada_por_id_ef7132f7 ON public.alumnos_transaccionsaldo USING btree (realizada_por_id);


--
-- Name: alumnos_transaccionsaldo_validada_por_id_b92f3132; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX alumnos_transaccionsaldo_validada_por_id_b92f3132 ON public.alumnos_transaccionsaldo USING btree (validada_por_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: compras_compra_numero_factura_0818ad8f_like; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX compras_compra_numero_factura_0818ad8f_like ON public.compras_compra USING btree (numero_factura varchar_pattern_ops);


--
-- Name: compras_compra_proveedor_id_d647dfa3; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX compras_compra_proveedor_id_d647dfa3 ON public.compras_compra USING btree (proveedor_id);


--
-- Name: compras_detallecompra_compra_id_9d6236ea; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX compras_detallecompra_compra_id_9d6236ea ON public.compras_detallecompra USING btree (compra_id);


--
-- Name: compras_detallecompra_producto_id_38c7f9c4; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX compras_detallecompra_producto_id_38c7f9c4 ON public.compras_detallecompra USING btree (producto_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: facturacion_factura_numero_ecc88d1d_like; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX facturacion_factura_numero_ecc88d1d_like ON public.facturacion_factura USING btree (numero varchar_pattern_ops);


--
-- Name: productos_movimientostock_producto_id_d5fbed3d; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX productos_movimientostock_producto_id_d5fbed3d ON public.productos_movimientostock USING btree (producto_id);


--
-- Name: productos_movimientostock_usuario_id_4f3a74fd; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX productos_movimientostock_usuario_id_4f3a74fd ON public.productos_movimientostock USING btree (usuario_id);


--
-- Name: productos_p_categor_17b5fc_idx; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX productos_p_categor_17b5fc_idx ON public.productos_producto USING btree (categoria_id);


--
-- Name: productos_p_codigo__7c1f60_idx; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX productos_p_codigo__7c1f60_idx ON public.productos_producto USING btree (codigo_barras);


--
-- Name: productos_p_codigo_bbe51f_idx; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX productos_p_codigo_bbe51f_idx ON public.productos_producto USING btree (codigo);


--
-- Name: productos_p_estado_ec69d1_idx; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX productos_p_estado_ec69d1_idx ON public.productos_producto USING btree (estado);


--
-- Name: productos_producto_categoria_id_1fef506a; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX productos_producto_categoria_id_1fef506a ON public.productos_producto USING btree (categoria_id);


--
-- Name: productos_producto_codigo_791f094d_like; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX productos_producto_codigo_791f094d_like ON public.productos_producto USING btree (codigo varchar_pattern_ops);


--
-- Name: productos_producto_proveedor_id_3ef13ee3; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX productos_producto_proveedor_id_3ef13ee3 ON public.productos_producto USING btree (proveedor_id);


--
-- Name: usuarios_usuariolg_groups_group_id_05fbae48; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX usuarios_usuariolg_groups_group_id_05fbae48 ON public.usuarios_usuariolg_groups USING btree (group_id);


--
-- Name: usuarios_usuariolg_groups_usuariolg_id_ded26d57; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX usuarios_usuariolg_groups_usuariolg_id_ded26d57 ON public.usuarios_usuariolg_groups USING btree (usuariolg_id);


--
-- Name: usuarios_usuariolg_user_permissions_permission_id_4c83cefe; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX usuarios_usuariolg_user_permissions_permission_id_4c83cefe ON public.usuarios_usuariolg_user_permissions USING btree (permission_id);


--
-- Name: usuarios_usuariolg_user_permissions_usuariolg_id_d0999ad2; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX usuarios_usuariolg_user_permissions_usuariolg_id_d0999ad2 ON public.usuarios_usuariolg_user_permissions USING btree (usuariolg_id);


--
-- Name: usuarios_usuariolg_username_7468bf94_like; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX usuarios_usuariolg_username_7468bf94_like ON public.usuarios_usuariolg USING btree (username varchar_pattern_ops);


--
-- Name: ventas_authorizationcode_venta_id_d28707fd; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX ventas_authorizationcode_venta_id_d28707fd ON public.ventas_authorizationcode USING btree (venta_id);


--
-- Name: ventas_detalleventa_producto_id_a820c807; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX ventas_detalleventa_producto_id_a820c807 ON public.ventas_detalleventa USING btree (producto_id);


--
-- Name: ventas_detalleventa_venta_id_c370bcd7; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX ventas_detalleventa_venta_id_c370bcd7 ON public.ventas_detalleventa USING btree (venta_id);


--
-- Name: ventas_metodopago_nombre_8e538c02_like; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX ventas_metodopago_nombre_8e538c02_like ON public.ventas_metodopago USING btree (nombre varchar_pattern_ops);


--
-- Name: ventas_pagoventa_metodo_pago_id_79c0619d; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX ventas_pagoventa_metodo_pago_id_79c0619d ON public.ventas_pagoventa USING btree (metodo_pago_id);


--
-- Name: ventas_pagoventa_venta_id_d59f2534; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX ventas_pagoventa_venta_id_d59f2534 ON public.ventas_pagoventa USING btree (venta_id);


--
-- Name: ventas_reportecaja_caja_id_eed362fe; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX ventas_reportecaja_caja_id_eed362fe ON public.ventas_reportecaja USING btree (caja_id);


--
-- Name: ventas_turnocajero_caja_id_bd116620; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX ventas_turnocajero_caja_id_bd116620 ON public.ventas_turnocajero USING btree (caja_id);


--
-- Name: ventas_turnocajero_cajero_id_8789390e; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX ventas_turnocajero_cajero_id_8789390e ON public.ventas_turnocajero USING btree (cajero_id);


--
-- Name: ventas_venta_cajero_id_3154b50f; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX ventas_venta_cajero_id_3154b50f ON public.ventas_venta USING btree (cajero_id);


--
-- Name: ventas_venta_cliente_id_85f33a80; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX ventas_venta_cliente_id_85f33a80 ON public.ventas_venta USING btree (cliente_id);


--
-- Name: ventas_venta_numero_venta_21ad7b3e_like; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX ventas_venta_numero_venta_21ad7b3e_like ON public.ventas_venta USING btree (numero_venta varchar_pattern_ops);


--
-- Name: ventas_venta_turno_cajero_id_12d6539b; Type: INDEX; Schema: public; Owner: lgservice_user
--

CREATE INDEX ventas_venta_turno_cajero_id_12d6539b ON public.ventas_venta USING btree (turno_cajero_id);


--
-- Name: alumnos_notificacionpadre alumnos_notificacion_alumno_id_b844dd96_fk_alumnos_a; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_notificacionpadre
    ADD CONSTRAINT alumnos_notificacion_alumno_id_b844dd96_fk_alumnos_a FOREIGN KEY (alumno_id) REFERENCES public.alumnos_alumno(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alumnos_notificacionpadre alumnos_notificacion_transaccion_id_2a6a818d_fk_alumnos_t; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_notificacionpadre
    ADD CONSTRAINT alumnos_notificacion_transaccion_id_2a6a818d_fk_alumnos_t FOREIGN KEY (transaccion_id) REFERENCES public.alumnos_transaccionsaldo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alumnos_notificacionpadre alumnos_notificacionpadre_padre_id_e22c6c55_fk_alumnos_padre_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_notificacionpadre
    ADD CONSTRAINT alumnos_notificacionpadre_padre_id_e22c6c55_fk_alumnos_padre_id FOREIGN KEY (padre_id) REFERENCES public.alumnos_padre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alumnos_notificacionpadre alumnos_notificacionpadre_venta_id_d8d6d2f5_fk_ventas_venta_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_notificacionpadre
    ADD CONSTRAINT alumnos_notificacionpadre_venta_id_d8d6d2f5_fk_ventas_venta_id FOREIGN KEY (venta_id) REFERENCES public.ventas_venta(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alumnos_padre alumnos_padre_usuario_id_183fb53d_fk_usuarios_usuariolg_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_padre
    ADD CONSTRAINT alumnos_padre_usuario_id_183fb53d_fk_usuarios_usuariolg_id FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuariolg(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alumnos_relacionfamiliar alumnos_relacionfami_alumno_id_11dc7f0a_fk_alumnos_a; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_relacionfamiliar
    ADD CONSTRAINT alumnos_relacionfami_alumno_id_11dc7f0a_fk_alumnos_a FOREIGN KEY (alumno_id) REFERENCES public.alumnos_alumno(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alumnos_relacionfamiliar alumnos_relacionfamiliar_padre_id_b20e606e_fk_alumnos_padre_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_relacionfamiliar
    ADD CONSTRAINT alumnos_relacionfamiliar_padre_id_b20e606e_fk_alumnos_padre_id FOREIGN KEY (padre_id) REFERENCES public.alumnos_padre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alumnos_restriccion alumnos_restriccion_alumno_id_15a1a8ba_fk_alumnos_alumno_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_restriccion
    ADD CONSTRAINT alumnos_restriccion_alumno_id_15a1a8ba_fk_alumnos_alumno_id FOREIGN KEY (alumno_id) REFERENCES public.alumnos_alumno(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alumnos_restriccion alumnos_restriccion_producto_id_c8ff6278_fk_productos; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_restriccion
    ADD CONSTRAINT alumnos_restriccion_producto_id_c8ff6278_fk_productos FOREIGN KEY (producto_id) REFERENCES public.productos_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alumnos_transaccionsaldo alumnos_transaccions_alumno_id_05386095_fk_alumnos_a; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_transaccionsaldo
    ADD CONSTRAINT alumnos_transaccions_alumno_id_05386095_fk_alumnos_a FOREIGN KEY (alumno_id) REFERENCES public.alumnos_alumno(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alumnos_transaccionsaldo alumnos_transaccions_realizada_por_id_ef7132f7_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_transaccionsaldo
    ADD CONSTRAINT alumnos_transaccions_realizada_por_id_ef7132f7_fk_usuarios_ FOREIGN KEY (realizada_por_id) REFERENCES public.usuarios_usuariolg(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: alumnos_transaccionsaldo alumnos_transaccions_validada_por_id_b92f3132_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.alumnos_transaccionsaldo
    ADD CONSTRAINT alumnos_transaccions_validada_por_id_b92f3132_fk_usuarios_ FOREIGN KEY (validada_por_id) REFERENCES public.usuarios_usuariolg(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: compras_compra compras_compra_proveedor_id_d647dfa3_fk_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.compras_compra
    ADD CONSTRAINT compras_compra_proveedor_id_d647dfa3_fk_proveedor FOREIGN KEY (proveedor_id) REFERENCES public.proveedores_proveedor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: compras_detallecompra compras_detallecompr_producto_id_38c7f9c4_fk_productos; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.compras_detallecompra
    ADD CONSTRAINT compras_detallecompr_producto_id_38c7f9c4_fk_productos FOREIGN KEY (producto_id) REFERENCES public.productos_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: compras_detallecompra compras_detallecompra_compra_id_9d6236ea_fk_compras_compra_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.compras_detallecompra
    ADD CONSTRAINT compras_detallecompra_compra_id_9d6236ea_fk_compras_compra_id FOREIGN KEY (compra_id) REFERENCES public.compras_compra(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_usuarios_usuariolg_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_usuarios_usuariolg_id FOREIGN KEY (user_id) REFERENCES public.usuarios_usuariolg(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: facturacion_factura facturacion_factura_venta_id_abf3f20d_fk_ventas_venta_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.facturacion_factura
    ADD CONSTRAINT facturacion_factura_venta_id_abf3f20d_fk_ventas_venta_id FOREIGN KEY (venta_id) REFERENCES public.ventas_venta(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_movimientostock productos_movimiento_producto_id_d5fbed3d_fk_productos; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.productos_movimientostock
    ADD CONSTRAINT productos_movimiento_producto_id_d5fbed3d_fk_productos FOREIGN KEY (producto_id) REFERENCES public.productos_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_movimientostock productos_movimiento_usuario_id_4f3a74fd_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.productos_movimientostock
    ADD CONSTRAINT productos_movimiento_usuario_id_4f3a74fd_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuariolg(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_producto productos_producto_categoria_id_1fef506a_fk_productos; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.productos_producto
    ADD CONSTRAINT productos_producto_categoria_id_1fef506a_fk_productos FOREIGN KEY (categoria_id) REFERENCES public.productos_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_producto productos_producto_proveedor_id_3ef13ee3_fk_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.productos_producto
    ADD CONSTRAINT productos_producto_proveedor_id_3ef13ee3_fk_proveedor FOREIGN KEY (proveedor_id) REFERENCES public.proveedores_proveedor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuariolg_groups usuarios_usuariolg_g_usuariolg_id_ded26d57_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.usuarios_usuariolg_groups
    ADD CONSTRAINT usuarios_usuariolg_g_usuariolg_id_ded26d57_fk_usuarios_ FOREIGN KEY (usuariolg_id) REFERENCES public.usuarios_usuariolg(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuariolg_groups usuarios_usuariolg_groups_group_id_05fbae48_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.usuarios_usuariolg_groups
    ADD CONSTRAINT usuarios_usuariolg_groups_group_id_05fbae48_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuariolg_user_permissions usuarios_usuariolg_u_permission_id_4c83cefe_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.usuarios_usuariolg_user_permissions
    ADD CONSTRAINT usuarios_usuariolg_u_permission_id_4c83cefe_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuariolg_user_permissions usuarios_usuariolg_u_usuariolg_id_d0999ad2_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.usuarios_usuariolg_user_permissions
    ADD CONSTRAINT usuarios_usuariolg_u_usuariolg_id_d0999ad2_fk_usuarios_ FOREIGN KEY (usuariolg_id) REFERENCES public.usuarios_usuariolg(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_authorizationcode ventas_authorizationcode_venta_id_d28707fd_fk_ventas_venta_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_authorizationcode
    ADD CONSTRAINT ventas_authorizationcode_venta_id_d28707fd_fk_ventas_venta_id FOREIGN KEY (venta_id) REFERENCES public.ventas_venta(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_detalleventa ventas_detalleventa_producto_id_a820c807_fk_productos; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_detalleventa
    ADD CONSTRAINT ventas_detalleventa_producto_id_a820c807_fk_productos FOREIGN KEY (producto_id) REFERENCES public.productos_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_detalleventa ventas_detalleventa_venta_id_c370bcd7_fk_ventas_venta_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_detalleventa
    ADD CONSTRAINT ventas_detalleventa_venta_id_c370bcd7_fk_ventas_venta_id FOREIGN KEY (venta_id) REFERENCES public.ventas_venta(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_pagoventa ventas_pagoventa_metodo_pago_id_79c0619d_fk_ventas_me; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_pagoventa
    ADD CONSTRAINT ventas_pagoventa_metodo_pago_id_79c0619d_fk_ventas_me FOREIGN KEY (metodo_pago_id) REFERENCES public.ventas_metodopago(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_pagoventa ventas_pagoventa_venta_id_d59f2534_fk_ventas_venta_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_pagoventa
    ADD CONSTRAINT ventas_pagoventa_venta_id_d59f2534_fk_ventas_venta_id FOREIGN KEY (venta_id) REFERENCES public.ventas_venta(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_reportecaja ventas_reportecaja_caja_id_eed362fe_fk_ventas_caja_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_reportecaja
    ADD CONSTRAINT ventas_reportecaja_caja_id_eed362fe_fk_ventas_caja_id FOREIGN KEY (caja_id) REFERENCES public.ventas_caja(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_turnocajero ventas_turnocajero_caja_id_bd116620_fk_ventas_caja_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_turnocajero
    ADD CONSTRAINT ventas_turnocajero_caja_id_bd116620_fk_ventas_caja_id FOREIGN KEY (caja_id) REFERENCES public.ventas_caja(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_turnocajero ventas_turnocajero_cajero_id_8789390e_fk_usuarios_usuariolg_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_turnocajero
    ADD CONSTRAINT ventas_turnocajero_cajero_id_8789390e_fk_usuarios_usuariolg_id FOREIGN KEY (cajero_id) REFERENCES public.usuarios_usuariolg(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_venta ventas_venta_cajero_id_3154b50f_fk_usuarios_usuariolg_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_venta
    ADD CONSTRAINT ventas_venta_cajero_id_3154b50f_fk_usuarios_usuariolg_id FOREIGN KEY (cajero_id) REFERENCES public.usuarios_usuariolg(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_venta ventas_venta_cliente_id_85f33a80_fk_alumnos_alumno_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_venta
    ADD CONSTRAINT ventas_venta_cliente_id_85f33a80_fk_alumnos_alumno_id FOREIGN KEY (cliente_id) REFERENCES public.alumnos_alumno(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_venta ventas_venta_turno_cajero_id_12d6539b_fk_ventas_turnocajero_id; Type: FK CONSTRAINT; Schema: public; Owner: lgservice_user
--

ALTER TABLE ONLY public.ventas_venta
    ADD CONSTRAINT ventas_venta_turno_cajero_id_12d6539b_fk_ventas_turnocajero_id FOREIGN KEY (turno_cajero_id) REFERENCES public.ventas_turnocajero(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

