# Generated by Django 5.2.7 on 2025-10-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_detalleventa_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoventa',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TRANSFERENCIA', 'Transferencia'), ('QR_WALLET', 'QR/Wallet'), ('SALDO', 'Saldo prepago'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='monto_final',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto + comisión', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='referencia',
            field=models.CharField(blank=True, help_text='Número de comprobante/referencia', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagoventa',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tasa de comisión (%)', max_digits=5),
        ),
    ]
