# Generated by Django 4.2.16 on 2025-10-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='LGservice', max_length=100)),
                ('moneda', models.CharField(default='Gs.', max_length=10)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horario_atencion', models.CharField(default='07:00 a 17:00', max_length=100)),
                ('color_principal', models.CharField(default='#16a34a', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
