# Generated by Django 5.2.7 on 2025-10-04 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={'verbose_name': 'Configuración del Sistema', 'verbose_name_plural': 'Configuraciones del Sistema'},
        ),
    ]
