# Generated by Django 5.2.2 on 2025-06-07 03:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('formato', models.CharField(choices=[('IMPRESA', 'Impresa'), ('ELECTRONICA', 'Electrónica')], default='IMPRESA', max_length=12)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='ventas.venta')),
            ],
            options={
                'ordering': ['-fecha_emision', 'numero'],
            },
        ),
    ]
