# Generated by Django 4.2.16 on 2025-10-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario - Cantina de Tita', 'verbose_name_plural': 'Usuarios - Cantina de Tita'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('administrador', '👑 Administrador'), ('cajero', '💰 Cajero'), ('padre', '👨\u200d👩\u200d👧\u200d👦 Padre/Tutor'), ('supervisor', '👨\u200d💼 Supervisor')], default='cajero', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
