# Generated by Django 5.2.2 on 2025-06-10 03:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grado', models.CharField(blank=True, max_length=50)),
                ('nivel', models.CharField(blank=True, max_length=50)),
                ('limite_consumo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto máximo que el alumno puede gastar por día', max_digits=10)),
                ('saldo_tarjeta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo cargado en la tarjeta prepaga (uso exclusivo Cantina)', max_digits=12)),
                ('numero_tarjeta', models.CharField(blank=True, help_text='Número de tarjeta (uso exclusivo de La Cantina de Tita).', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('razon_social', models.CharField(blank=True, help_text='Razón social (si aplica). Dejar vacío si no corresponde.', max_length=150)),
                ('ruc', models.CharField(blank=True, help_text='RUC para facturación (si corresponde).', max_length=20)),
                ('email', models.EmailField(help_text='Correo para envío de factura electrónica.', max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('barrio', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitido', models.BooleanField(default=True, help_text='True=puede comprar, False=no puede')),
            ],
            options={
                'verbose_name': 'Restricción',
                'verbose_name_plural': 'Restricciones',
            },
        ),
    ]
