# Generated by Django 4.2.16 on 2025-10-08 18:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=20, unique=True, verbose_name='Número de Tarjeta')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('fecha_nacimiento', models.DateField()),
                ('grado', models.CharField(blank=True, choices=[('1ro', '1er Grado'), ('2do', '2do Grado'), ('3ro', '3er Grado'), ('4to', '4to Grado'), ('5to', '5to Grado'), ('6to', '6to Grado')], max_length=5, null=True, verbose_name='Grado')),
                ('seccion', models.CharField(blank=True, max_length=2, null=True, verbose_name='Sección')),
                ('saldo_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Curso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_tarjeta', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Transacción de Tarjeta',
                'verbose_name_plural': 'Transacciones de Tarjeta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recarga', 'Recarga'), ('compra', 'Compra'), ('devolucion', 'Devolución')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudRecarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recarga', to='alumnos.alumno')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recarga', to=settings.AUTH_USER_MODEL)),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_procesadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Recarga',
                'verbose_name_plural': 'Solicitudes de Recarga',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('ruc', models.CharField(max_length=20, unique=True, verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Fijo')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Padre/Tutor',
                'verbose_name_plural': 'Padres/Tutores',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['ruc'], name='alumnos_pad_ruc_3025f0_idx'), models.Index(fields=['ci'], name='alumnos_pad_ci_eefc6c_idx'), models.Index(fields=['email'], name='alumnos_pad_email_5eb402_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carga', 'Carga de Saldo'), ('compra', 'Compra'), ('ajuste', 'Ajuste Manual'), ('devolucion', 'Devolución')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='alumnos.alumno')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Saldo',
                'verbose_name_plural': 'Movimientos de Saldo',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='padre_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='alumnos.padre', verbose_name='Padre/Tutor'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['numero_tarjeta'], name='alumnos_alu_numero__ff7719_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['ci'], name='alumnos_alu_ci_1077e0_idx'),
        ),
    ]
