# Generated by Django 5.2.2 on 2025-06-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='numero_tarjeta',
            field=models.CharField(blank=True, help_text='Número de tarjeta (uso exclusivo de La Cantina de Tita).', max_length=20, null=True),
        ),
    ]
