# Generated by Django 5.2.2 on 2025-06-10 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='padre',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='padre_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumno',
            name='padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='alumnos.padre'),
        ),
        migrations.AddField(
            model_name='restriccion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones', to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='restriccion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones_por_alumno', to='productos.producto'),
        ),
        migrations.AddConstraint(
            model_name='restriccion',
            constraint=models.UniqueConstraint(fields=('alumno', 'producto'), name='unique_restriccion_alumno_producto'),
        ),
    ]
