# Generated by Django 5.2.7 on 2025-10-04 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('ventas', '0003_pagoventa_aprobado_alter_pagoventa_metodo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRecarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('deposito', 'Depósito Bancario'), ('efectivo', 'Pago en Efectivo'), ('cheque', 'Cheque')], max_length=20)),
                ('referencia_pago', models.CharField(blank=True, help_text='Número de referencia del pago', max_length=100, null=True)),
                ('comprobante', models.FileField(help_text='Suba el comprobante de pago (JPG, PNG, PDF)', upload_to='comprobantes_recarga/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('procesada', 'Procesada')], default='pendiente', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('observaciones_admin', models.TextField(blank=True, null=True)),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recarga', to='alumnos.alumno')),
                ('padre_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('procesada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_procesadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Recarga',
                'verbose_name_plural': 'Solicitudes de Recarga',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionPadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.CharField(choices=[('solicitud_recibida', 'Solicitud Recibida'), ('solicitud_aprobada', 'Solicitud Aprobada'), ('solicitud_rechazada', 'Solicitud Rechazada'), ('saldo_bajo', 'Saldo Bajo'), ('consumo_limite', 'Límite de Consumo Alcanzado')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_padre', to='alumnos.alumno')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('solicitud_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnos.solicitudrecarga')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.CharField(choices=[('recarga_aprobada', 'Recarga Aprobada'), ('consumo_venta', 'Consumo por Venta'), ('ajuste_positivo', 'Ajuste Positivo'), ('ajuste_negativo', 'Ajuste Negativo'), ('devolucion', 'Devolución')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Positivo para créditos, negativo para débitos', max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_saldo', to='alumnos.alumno')),
                ('procesada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitud_recarga', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaccion_generada', to='alumnos.solicitudrecarga')),
                ('venta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_saldo', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Transacción de Saldo',
                'verbose_name_plural': 'Transacciones de Saldo',
                'ordering': ['-fecha_transaccion'],
            },
        ),
    ]
