# Generated by Django 5.2.7 on 2025-10-04 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_solicitudrecarga_notificacionpadre_transaccionsaldo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recarga', 'Recarga de Saldo'), ('consumo', 'Consumo'), ('ajuste', 'Ajuste Manual'), ('devolucion', 'Devolución')], default='consumo', max_length=20, verbose_name='Tipo de transacción')),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada'), ('error', 'Error')], default='completada', max_length=20, verbose_name='Estado')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la transacción en guaraníes', max_digits=10, verbose_name='Monto')),
                ('descripcion', models.CharField(help_text='Descripción detallada de la transacción', max_length=200, verbose_name='Descripción')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, help_text='Saldo antes de la transacción', max_digits=10, verbose_name='Saldo anterior')),
                ('saldo_posterior', models.DecimalField(decimal_places=2, help_text='Saldo después de la transacción', max_digits=10, verbose_name='Saldo posterior')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('numero_comprobante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de comprobante')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='notificacionpadre',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='notificacionpadre',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='notificacionpadre',
            name='solicitud_relacionada',
        ),
        migrations.RemoveField(
            model_name='transaccionsaldo',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='transaccionsaldo',
            name='procesada_por',
        ),
        migrations.RemoveField(
            model_name='transaccionsaldo',
            name='solicitud_recarga',
        ),
        migrations.RemoveField(
            model_name='transaccionsaldo',
            name='venta_relacionada',
        ),
        migrations.AlterModelOptions(
            name='transacciontarjeta',
            options={'ordering': ['-fecha'], 'verbose_name': 'Transacción de Tarjeta (Legacy)', 'verbose_name_plural': 'Transacciones de Tarjeta (Legacy)'},
        ),
        migrations.RemoveField(
            model_name='solicitudrecarga',
            name='comprobante',
        ),
        migrations.RemoveField(
            model_name='solicitudrecarga',
            name='observaciones_admin',
        ),
        migrations.RemoveField(
            model_name='solicitudrecarga',
            name='procesada_por',
        ),
        migrations.AddField(
            model_name='solicitudrecarga',
            name='comprobante_pago',
            field=models.ImageField(blank=True, help_text='Subir imagen del comprobante de pago', null=True, upload_to='comprobantes_recarga/', verbose_name='Comprobante de pago'),
        ),
        migrations.AddField(
            model_name='solicitudrecarga',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de comprobante'),
        ),
        migrations.AddField(
            model_name='solicitudrecarga',
            name='observaciones_procesamiento',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del procesamiento'),
        ),
        migrations.AddField(
            model_name='solicitudrecarga',
            name='usuario_procesador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Procesado por'),
        ),
        migrations.AlterField(
            model_name='solicitudrecarga',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recarga', to='alumnos.alumno', verbose_name='Alumno'),
        ),
        migrations.AlterField(
            model_name='solicitudrecarga',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('procesada', 'Procesada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='solicitudrecarga',
            name='fecha_procesamiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento'),
        ),
        migrations.AlterField(
            model_name='solicitudrecarga',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitudrecarga',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('deposito', 'Depósito Bancario'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='solicitudrecarga',
            name='monto_aprobado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto aprobado'),
        ),
        migrations.AlterField(
            model_name='solicitudrecarga',
            name='monto_solicitado',
            field=models.DecimalField(decimal_places=2, help_text='Monto a recargar en guaraníes', max_digits=10, verbose_name='Monto solicitado'),
        ),
        migrations.AlterField(
            model_name='solicitudrecarga',
            name='padre_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Padre solicitante'),
        ),
        migrations.AlterField(
            model_name='transacciontarjeta',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_tarjeta', to='alumnos.alumno'),
        ),
        migrations.AddIndex(
            model_name='solicitudrecarga',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='alumnos_sol_estado_620f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudrecarga',
            index=models.Index(fields=['alumno', 'estado'], name='alumnos_sol_alumno__7f2211_idx'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_saldo', to='alumnos.alumno', verbose_name='Alumno'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='referencia_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumnos.solicitudrecarga', verbose_name='Solicitud asociada'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='usuario_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable'),
        ),
        migrations.DeleteModel(
            name='NotificacionPadre',
        ),
        migrations.DeleteModel(
            name='TransaccionSaldo',
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['alumno', 'fecha'], name='alumnos_tra_alumno__ba003b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['tipo', 'estado'], name='alumnos_tra_tipo_dc5353_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['fecha'], name='alumnos_tra_fecha_8ae766_idx'),
        ),
    ]
