# Generated by Django 5.2.7 on 2025-10-06 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_transaccion_remove_notificacionpadre_alumno_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('saldo_bajo', 'Saldo Bajo'), ('transaccion', 'Nueva Transacción'), ('solicitud', 'Solicitud de Recarga'), ('limite_consumo', 'Límite de Consumo'), ('sistema', 'Sistema')], max_length=20)),
                ('nivel', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito')], default='info', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('url_accion', models.CharField(blank=True, max_length=255, null=True)),
                ('texto_accion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='alumno',
            name='numero_matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['apellido', 'nombre'], name='alumnos_alu_apellid_b81438_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['numero_matricula'], name='alumnos_alu_numero__c82502_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['numero_tarjeta'], name='alumnos_alu_numero__ff7719_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['estado', 'curso'], name='alumnos_alu_estado_a7d3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['saldo_tarjeta'], name='alumnos_alu_saldo_t_70296c_idx'),
        ),
        migrations.AddIndex(
            model_name='alumno',
            index=models.Index(fields=['fecha_creacion'], name='alumnos_alu_fecha_c_2a3928_idx'),
        ),
        migrations.AddIndex(
            model_name='padre',
            index=models.Index(fields=['apellido', 'nombre'], name='alumnos_pad_apellid_9ef44c_idx'),
        ),
        migrations.AddIndex(
            model_name='padre',
            index=models.Index(fields=['email'], name='alumnos_pad_email_5eb402_idx'),
        ),
        migrations.AddIndex(
            model_name='padre',
            index=models.Index(fields=['fecha_creacion'], name='alumnos_pad_fecha_c_298b93_idx'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', '-fecha_creacion'], name='alumnos_not_usuario_50fa46_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo'], name='alumnos_not_tipo_137f94_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['leida'], name='alumnos_not_leida_17ec8b_idx'),
        ),
    ]
