# Generated by Django 5.2.2 on 2025-06-07 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, help_text='Datos de contacto (teléfono o email) del proveedor (opcional).', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno o manual que identifica al producto', max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Stock disponible (unidades)')),
                ('precio_costo', models.DecimalField(decimal_places=2, help_text='Precio de costo en Gs.', max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio de venta en Gs.', max_digits=10)),
                ('categoria', models.CharField(blank=True, help_text='Categoría (por ej. Bebidas, Snacks, etc.)', max_length=50)),
                ('proveedor', models.ForeignKey(blank=True, help_text='Proveedor de este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.proveedor')),
            ],
        ),
    ]
