# Generated by Django 4.2.16 on 2025-10-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('nombre_comercial', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('tipo_documento', models.CharField(choices=[('ruc', 'RUC'), ('dni', 'DNI'), ('ce', 'Carnet de Extranjería'), ('otro', 'Otro')], default='ruc', max_length=10)),
                ('numero_documento', models.CharField(db_index=True, max_length=20, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rubro', models.CharField(blank=True, max_length=100, null=True)),
                ('condiciones_pago', models.TextField(blank=True, null=True)),
                ('tiempo_entrega_promedio', models.PositiveIntegerField(blank=True, help_text='Tiempo promedio de entrega en días', null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('ultima_compra', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
    ]
